### ISSUE TITLE
Slack用のメッセージ

### ISSUE THREAD

**Issue by trainshogi** [gidoichi/notboard#2]
Slack用にメッセージを変えてほしいです。
最初の3行（時間とか）は要らないので、
次の4行目を強調文字(*)で囲ってほしいです。
自分で直したいのですが、場所がわからないので直してください。

**Comment by gidoichi** [comment]
分かりやすさの観点からタイトルを強調は行います。送信のエラーにより掲示板での新着情報がその日中に配信されない可能性があるため、日時の情報はこのまま残しておきます。
